// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: asset_frame_snapshots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAssetFrameSnapshotsByAsset = `-- name: DeleteAssetFrameSnapshotsByAsset :exec
DELETE FROM asset_frame_snapshots
WHERE asset_id = $1
`

func (q *Queries) DeleteAssetFrameSnapshotsByAsset(ctx context.Context, assetID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssetFrameSnapshotsByAsset, assetID)
	return err
}

const listAssetFrameSnapshotsByAsset = `-- name: ListAssetFrameSnapshotsByAsset :many
SELECT id, asset_id, frame_index, timestamp_ms, storage_key, width, height, created_at
FROM asset_frame_snapshots
WHERE asset_id = $1
ORDER BY frame_index ASC, created_at ASC
`

func (q *Queries) ListAssetFrameSnapshotsByAsset(ctx context.Context, assetID pgtype.UUID) ([]AssetFrameSnapshot, error) {
	rows, err := q.db.Query(ctx, listAssetFrameSnapshotsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetFrameSnapshot
	for rows.Next() {
		var i AssetFrameSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.FrameIndex,
			&i.TimestampMs,
			&i.StorageKey,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssetFrameSnapshot = `-- name: UpsertAssetFrameSnapshot :one
INSERT INTO asset_frame_snapshots (
    asset_id,
    frame_index,
    timestamp_ms,
    storage_key,
    width,
    height
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (asset_id, frame_index)
DO UPDATE SET
    timestamp_ms = EXCLUDED.timestamp_ms,
    storage_key = EXCLUDED.storage_key,
    width = EXCLUDED.width,
    height = EXCLUDED.height
RETURNING id, asset_id, frame_index, timestamp_ms, storage_key, width, height, created_at
`

type UpsertAssetFrameSnapshotParams struct {
	AssetID     pgtype.UUID `json:"asset_id"`
	FrameIndex  int32       `json:"frame_index"`
	TimestampMs int32       `json:"timestamp_ms"`
	StorageKey  string      `json:"storage_key"`
	Width       pgtype.Int4 `json:"width"`
	Height      pgtype.Int4 `json:"height"`
}

func (q *Queries) UpsertAssetFrameSnapshot(ctx context.Context, arg UpsertAssetFrameSnapshotParams) (AssetFrameSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertAssetFrameSnapshot,
		arg.AssetID,
		arg.FrameIndex,
		arg.TimestampMs,
		arg.StorageKey,
		arg.Width,
		arg.Height,
	)
	var i AssetFrameSnapshot
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.FrameIndex,
		&i.TimestampMs,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}
