// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: asset_selling_points.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAssetSellingPoint = `-- name: AddAssetSellingPoint :exec
INSERT INTO asset_selling_points (
    asset_id,
    selling_point_id
) VALUES (
    $1, $2
)
ON CONFLICT DO NOTHING
`

type AddAssetSellingPointParams struct {
	AssetID        pgtype.UUID `json:"asset_id"`
	SellingPointID pgtype.UUID `json:"selling_point_id"`
}

func (q *Queries) AddAssetSellingPoint(ctx context.Context, arg AddAssetSellingPointParams) error {
	_, err := q.db.Exec(ctx, addAssetSellingPoint, arg.AssetID, arg.SellingPointID)
	return err
}

const listSellingPointIDsByAsset = `-- name: ListSellingPointIDsByAsset :many
SELECT selling_point_id
FROM asset_selling_points
WHERE asset_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSellingPointIDsByAsset(ctx context.Context, assetID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSellingPointIDsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var selling_point_id pgtype.UUID
		if err := rows.Scan(&selling_point_id); err != nil {
			return nil, err
		}
		items = append(items, selling_point_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAssetSellingPoint = `-- name: RemoveAssetSellingPoint :exec
DELETE FROM asset_selling_points
WHERE asset_id = $1
  AND selling_point_id = $2
`

type RemoveAssetSellingPointParams struct {
	AssetID        pgtype.UUID `json:"asset_id"`
	SellingPointID pgtype.UUID `json:"selling_point_id"`
}

func (q *Queries) RemoveAssetSellingPoint(ctx context.Context, arg RemoveAssetSellingPointParams) error {
	_, err := q.db.Exec(ctx, removeAssetSellingPoint, arg.AssetID, arg.SellingPointID)
	return err
}
