// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAsset = `-- name: ArchiveAsset :exec
UPDATE assets
SET status = 'archived',
    archived_at = now(),
    updated_by_user_id = $2,
    updated_at = now()
WHERE id = $1
`

type ArchiveAssetParams struct {
	ID              pgtype.UUID `json:"id"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) ArchiveAsset(ctx context.Context, arg ArchiveAssetParams) error {
	_, err := q.db.Exec(ctx, archiveAsset, arg.ID, arg.UpdatedByUserID)
	return err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    product_id,
    asset_name,
    storage_key,
    file_name,
    file_ext,
    mime_type,
    file_size,
    checksum,
    source_type,
    ingestion_source,
    duration_ms,
    width,
    height,
    fps,
    codec,
    status,
    analysis_status,
    usability_status,
    manual_clean_status,
    source_path,
    source_original_name,
    source_in_ms,
    source_out_ms,
    has_audio,
    audio_codec,
    bitrate_kbps,
    scene_description,
    shot_size,
    camera_movement,
    subjects,
    scene_tags,
    quality_tags,
    model_result,
    reviewer_notes,
    analysis_error,
    analyzed_at,
    metadata,
    created_by_user_id,
    updated_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33, $34, $35, $36, $37, $38, $38
)
RETURNING id, product_id, storage_key, file_name, file_ext, mime_type, file_size, checksum, source_type, duration_ms, width, height, fps, codec, status, manual_clean_status, source_original_name, source_in_ms, source_out_ms, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at, asset_name, source_path, ingestion_source, analysis_status, usability_status, has_audio, audio_codec, bitrate_kbps, scene_description, shot_size, camera_movement, subjects, scene_tags, quality_tags, model_result, reviewer_notes, analysis_error, analyzed_at, archived_at
`

type CreateAssetParams struct {
	ProductID          pgtype.UUID        `json:"product_id"`
	AssetName          pgtype.Text        `json:"asset_name"`
	StorageKey         string             `json:"storage_key"`
	FileName           string             `json:"file_name"`
	FileExt            pgtype.Text        `json:"file_ext"`
	MimeType           pgtype.Text        `json:"mime_type"`
	FileSize           int64              `json:"file_size"`
	Checksum           pgtype.Text        `json:"checksum"`
	SourceType         string             `json:"source_type"`
	IngestionSource    string             `json:"ingestion_source"`
	DurationMs         pgtype.Int4        `json:"duration_ms"`
	Width              pgtype.Int4        `json:"width"`
	Height             pgtype.Int4        `json:"height"`
	Fps                pgtype.Numeric     `json:"fps"`
	Codec              pgtype.Text        `json:"codec"`
	Status             string             `json:"status"`
	AnalysisStatus     string             `json:"analysis_status"`
	UsabilityStatus    string             `json:"usability_status"`
	ManualCleanStatus  string             `json:"manual_clean_status"`
	SourcePath         pgtype.Text        `json:"source_path"`
	SourceOriginalName pgtype.Text        `json:"source_original_name"`
	SourceInMs         pgtype.Int4        `json:"source_in_ms"`
	SourceOutMs        pgtype.Int4        `json:"source_out_ms"`
	HasAudio           bool               `json:"has_audio"`
	AudioCodec         pgtype.Text        `json:"audio_codec"`
	BitrateKbps        pgtype.Int4        `json:"bitrate_kbps"`
	SceneDescription   pgtype.Text        `json:"scene_description"`
	ShotSize           pgtype.Text        `json:"shot_size"`
	CameraMovement     pgtype.Text        `json:"camera_movement"`
	Subjects           []byte             `json:"subjects"`
	SceneTags          []byte             `json:"scene_tags"`
	QualityTags        []byte             `json:"quality_tags"`
	ModelResult        []byte             `json:"model_result"`
	ReviewerNotes      pgtype.Text        `json:"reviewer_notes"`
	AnalysisError      pgtype.Text        `json:"analysis_error"`
	AnalyzedAt         pgtype.Timestamptz `json:"analyzed_at"`
	Metadata           []byte             `json:"metadata"`
	CreatedByUserID    pgtype.UUID        `json:"created_by_user_id"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ProductID,
		arg.AssetName,
		arg.StorageKey,
		arg.FileName,
		arg.FileExt,
		arg.MimeType,
		arg.FileSize,
		arg.Checksum,
		arg.SourceType,
		arg.IngestionSource,
		arg.DurationMs,
		arg.Width,
		arg.Height,
		arg.Fps,
		arg.Codec,
		arg.Status,
		arg.AnalysisStatus,
		arg.UsabilityStatus,
		arg.ManualCleanStatus,
		arg.SourcePath,
		arg.SourceOriginalName,
		arg.SourceInMs,
		arg.SourceOutMs,
		arg.HasAudio,
		arg.AudioCodec,
		arg.BitrateKbps,
		arg.SceneDescription,
		arg.ShotSize,
		arg.CameraMovement,
		arg.Subjects,
		arg.SceneTags,
		arg.QualityTags,
		arg.ModelResult,
		arg.ReviewerNotes,
		arg.AnalysisError,
		arg.AnalyzedAt,
		arg.Metadata,
		arg.CreatedByUserID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StorageKey,
		&i.FileName,
		&i.FileExt,
		&i.MimeType,
		&i.FileSize,
		&i.Checksum,
		&i.SourceType,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.Codec,
		&i.Status,
		&i.ManualCleanStatus,
		&i.SourceOriginalName,
		&i.SourceInMs,
		&i.SourceOutMs,
		&i.Metadata,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssetName,
		&i.SourcePath,
		&i.IngestionSource,
		&i.AnalysisStatus,
		&i.UsabilityStatus,
		&i.HasAudio,
		&i.AudioCodec,
		&i.BitrateKbps,
		&i.SceneDescription,
		&i.ShotSize,
		&i.CameraMovement,
		&i.Subjects,
		&i.SceneTags,
		&i.QualityTags,
		&i.ModelResult,
		&i.ReviewerNotes,
		&i.AnalysisError,
		&i.AnalyzedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, product_id, storage_key, file_name, file_ext, mime_type, file_size, checksum, source_type, duration_ms, width, height, fps, codec, status, manual_clean_status, source_original_name, source_in_ms, source_out_ms, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at, asset_name, source_path, ingestion_source, analysis_status, usability_status, has_audio, audio_codec, bitrate_kbps, scene_description, shot_size, camera_movement, subjects, scene_tags, quality_tags, model_result, reviewer_notes, analysis_error, analyzed_at, archived_at FROM assets
WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StorageKey,
		&i.FileName,
		&i.FileExt,
		&i.MimeType,
		&i.FileSize,
		&i.Checksum,
		&i.SourceType,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.Codec,
		&i.Status,
		&i.ManualCleanStatus,
		&i.SourceOriginalName,
		&i.SourceInMs,
		&i.SourceOutMs,
		&i.Metadata,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssetName,
		&i.SourcePath,
		&i.IngestionSource,
		&i.AnalysisStatus,
		&i.UsabilityStatus,
		&i.HasAudio,
		&i.AudioCodec,
		&i.BitrateKbps,
		&i.SceneDescription,
		&i.ShotSize,
		&i.CameraMovement,
		&i.Subjects,
		&i.SceneTags,
		&i.QualityTags,
		&i.ModelResult,
		&i.ReviewerNotes,
		&i.AnalysisError,
		&i.AnalyzedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, product_id, storage_key, file_name, file_ext, mime_type, file_size, checksum, source_type, duration_ms, width, height, fps, codec, status, manual_clean_status, source_original_name, source_in_ms, source_out_ms, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at, asset_name, source_path, ingestion_source, analysis_status, usability_status, has_audio, audio_codec, bitrate_kbps, scene_description, shot_size, camera_movement, subjects, scene_tags, quality_tags, model_result, reviewer_notes, analysis_error, analyzed_at, archived_at FROM assets
WHERE product_id = COALESCE($1, product_id)
  AND source_type = COALESCE($2, source_type)
  AND status = COALESCE($3, status)
  AND analysis_status = COALESCE($4, analysis_status)
  AND usability_status = COALESCE($5, usability_status)
ORDER BY created_at DESC
`

type ListAssetsParams struct {
	ProductID       pgtype.UUID `json:"product_id"`
	SourceType      pgtype.Text `json:"source_type"`
	Status          pgtype.Text `json:"status"`
	AnalysisStatus  pgtype.Text `json:"analysis_status"`
	UsabilityStatus pgtype.Text `json:"usability_status"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.ProductID,
		arg.SourceType,
		arg.Status,
		arg.AnalysisStatus,
		arg.UsabilityStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StorageKey,
			&i.FileName,
			&i.FileExt,
			&i.MimeType,
			&i.FileSize,
			&i.Checksum,
			&i.SourceType,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.Codec,
			&i.Status,
			&i.ManualCleanStatus,
			&i.SourceOriginalName,
			&i.SourceInMs,
			&i.SourceOutMs,
			&i.Metadata,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssetName,
			&i.SourcePath,
			&i.IngestionSource,
			&i.AnalysisStatus,
			&i.UsabilityStatus,
			&i.HasAudio,
			&i.AudioCodec,
			&i.BitrateKbps,
			&i.SceneDescription,
			&i.ShotSize,
			&i.CameraMovement,
			&i.Subjects,
			&i.SceneTags,
			&i.QualityTags,
			&i.ModelResult,
			&i.ReviewerNotes,
			&i.AnalysisError,
			&i.AnalyzedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetAnalysis = `-- name: UpdateAssetAnalysis :exec
UPDATE assets
SET analysis_status = $2,
    usability_status = $3,
    scene_description = $4,
    shot_size = $5,
    camera_movement = $6,
    subjects = $7,
    scene_tags = $8,
    quality_tags = $9,
    model_result = $10,
    analysis_error = $11,
    analyzed_at = $12,
    updated_by_user_id = $13,
    updated_at = now()
WHERE id = $1
`

type UpdateAssetAnalysisParams struct {
	ID               pgtype.UUID        `json:"id"`
	AnalysisStatus   string             `json:"analysis_status"`
	UsabilityStatus  string             `json:"usability_status"`
	SceneDescription pgtype.Text        `json:"scene_description"`
	ShotSize         pgtype.Text        `json:"shot_size"`
	CameraMovement   pgtype.Text        `json:"camera_movement"`
	Subjects         []byte             `json:"subjects"`
	SceneTags        []byte             `json:"scene_tags"`
	QualityTags      []byte             `json:"quality_tags"`
	ModelResult      []byte             `json:"model_result"`
	AnalysisError    pgtype.Text        `json:"analysis_error"`
	AnalyzedAt       pgtype.Timestamptz `json:"analyzed_at"`
	UpdatedByUserID  pgtype.UUID        `json:"updated_by_user_id"`
}

func (q *Queries) UpdateAssetAnalysis(ctx context.Context, arg UpdateAssetAnalysisParams) error {
	_, err := q.db.Exec(ctx, updateAssetAnalysis,
		arg.ID,
		arg.AnalysisStatus,
		arg.UsabilityStatus,
		arg.SceneDescription,
		arg.ShotSize,
		arg.CameraMovement,
		arg.Subjects,
		arg.SceneTags,
		arg.QualityTags,
		arg.ModelResult,
		arg.AnalysisError,
		arg.AnalyzedAt,
		arg.UpdatedByUserID,
	)
	return err
}

const updateAssetMediaInfo = `-- name: UpdateAssetMediaInfo :exec
UPDATE assets
SET duration_ms = $2,
    width = $3,
    height = $4,
    fps = $5,
    codec = $6,
    has_audio = $7,
    audio_codec = $8,
    bitrate_kbps = $9,
    updated_by_user_id = $10,
    updated_at = now()
WHERE id = $1
`

type UpdateAssetMediaInfoParams struct {
	ID              pgtype.UUID    `json:"id"`
	DurationMs      pgtype.Int4    `json:"duration_ms"`
	Width           pgtype.Int4    `json:"width"`
	Height          pgtype.Int4    `json:"height"`
	Fps             pgtype.Numeric `json:"fps"`
	Codec           pgtype.Text    `json:"codec"`
	HasAudio        bool           `json:"has_audio"`
	AudioCodec      pgtype.Text    `json:"audio_codec"`
	BitrateKbps     pgtype.Int4    `json:"bitrate_kbps"`
	UpdatedByUserID pgtype.UUID    `json:"updated_by_user_id"`
}

func (q *Queries) UpdateAssetMediaInfo(ctx context.Context, arg UpdateAssetMediaInfoParams) error {
	_, err := q.db.Exec(ctx, updateAssetMediaInfo,
		arg.ID,
		arg.DurationMs,
		arg.Width,
		arg.Height,
		arg.Fps,
		arg.Codec,
		arg.HasAudio,
		arg.AudioCodec,
		arg.BitrateKbps,
		arg.UpdatedByUserID,
	)
	return err
}

const updateAssetReview = `-- name: UpdateAssetReview :exec
UPDATE assets
SET reviewer_notes = $2,
    usability_status = $3,
    updated_by_user_id = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateAssetReviewParams struct {
	ID              pgtype.UUID `json:"id"`
	ReviewerNotes   pgtype.Text `json:"reviewer_notes"`
	UsabilityStatus string      `json:"usability_status"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) UpdateAssetReview(ctx context.Context, arg UpdateAssetReviewParams) error {
	_, err := q.db.Exec(ctx, updateAssetReview,
		arg.ID,
		arg.ReviewerNotes,
		arg.UsabilityStatus,
		arg.UpdatedByUserID,
	)
	return err
}

const updateAssetStatus = `-- name: UpdateAssetStatus :exec
UPDATE assets
SET status = $2,
    updated_by_user_id = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateAssetStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	Status          string      `json:"status"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) error {
	_, err := q.db.Exec(ctx, updateAssetStatus, arg.ID, arg.Status, arg.UpdatedByUserID)
	return err
}
