// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    product_id,
    storage_key,
    file_name,
    file_ext,
    mime_type,
    file_size,
    checksum,
    source_type,
    duration_ms,
    width,
    height,
    fps,
    codec,
    status,
    manual_clean_status,
    source_original_name,
    source_in_ms,
    source_out_ms,
    metadata,
    created_by_user_id,
    updated_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $20
)
RETURNING id, product_id, storage_key, file_name, file_ext, mime_type, file_size, checksum, source_type, duration_ms, width, height, fps, codec, status, manual_clean_status, source_original_name, source_in_ms, source_out_ms, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type CreateAssetParams struct {
	ProductID          pgtype.UUID    `json:"product_id"`
	StorageKey         string         `json:"storage_key"`
	FileName           string         `json:"file_name"`
	FileExt            pgtype.Text    `json:"file_ext"`
	MimeType           pgtype.Text    `json:"mime_type"`
	FileSize           int64          `json:"file_size"`
	Checksum           pgtype.Text    `json:"checksum"`
	SourceType         string         `json:"source_type"`
	DurationMs         pgtype.Int4    `json:"duration_ms"`
	Width              pgtype.Int4    `json:"width"`
	Height             pgtype.Int4    `json:"height"`
	Fps                pgtype.Numeric `json:"fps"`
	Codec              pgtype.Text    `json:"codec"`
	Status             string         `json:"status"`
	ManualCleanStatus  string         `json:"manual_clean_status"`
	SourceOriginalName pgtype.Text    `json:"source_original_name"`
	SourceInMs         pgtype.Int4    `json:"source_in_ms"`
	SourceOutMs        pgtype.Int4    `json:"source_out_ms"`
	Metadata           []byte         `json:"metadata"`
	CreatedByUserID    pgtype.UUID    `json:"created_by_user_id"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ProductID,
		arg.StorageKey,
		arg.FileName,
		arg.FileExt,
		arg.MimeType,
		arg.FileSize,
		arg.Checksum,
		arg.SourceType,
		arg.DurationMs,
		arg.Width,
		arg.Height,
		arg.Fps,
		arg.Codec,
		arg.Status,
		arg.ManualCleanStatus,
		arg.SourceOriginalName,
		arg.SourceInMs,
		arg.SourceOutMs,
		arg.Metadata,
		arg.CreatedByUserID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StorageKey,
		&i.FileName,
		&i.FileExt,
		&i.MimeType,
		&i.FileSize,
		&i.Checksum,
		&i.SourceType,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.Codec,
		&i.Status,
		&i.ManualCleanStatus,
		&i.SourceOriginalName,
		&i.SourceInMs,
		&i.SourceOutMs,
		&i.Metadata,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, product_id, storage_key, file_name, file_ext, mime_type, file_size, checksum, source_type, duration_ms, width, height, fps, codec, status, manual_clean_status, source_original_name, source_in_ms, source_out_ms, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at FROM assets
WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StorageKey,
		&i.FileName,
		&i.FileExt,
		&i.MimeType,
		&i.FileSize,
		&i.Checksum,
		&i.SourceType,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.Codec,
		&i.Status,
		&i.ManualCleanStatus,
		&i.SourceOriginalName,
		&i.SourceInMs,
		&i.SourceOutMs,
		&i.Metadata,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, product_id, storage_key, file_name, file_ext, mime_type, file_size, checksum, source_type, duration_ms, width, height, fps, codec, status, manual_clean_status, source_original_name, source_in_ms, source_out_ms, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at FROM assets
WHERE product_id = COALESCE($1, product_id)
  AND source_type = COALESCE($2, source_type)
  AND status = COALESCE($3, status)
ORDER BY created_at DESC
`

type ListAssetsParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	SourceType pgtype.Text `json:"source_type"`
	Status     pgtype.Text `json:"status"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets, arg.ProductID, arg.SourceType, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StorageKey,
			&i.FileName,
			&i.FileExt,
			&i.MimeType,
			&i.FileSize,
			&i.Checksum,
			&i.SourceType,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.Codec,
			&i.Status,
			&i.ManualCleanStatus,
			&i.SourceOriginalName,
			&i.SourceInMs,
			&i.SourceOutMs,
			&i.Metadata,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetMediaInfo = `-- name: UpdateAssetMediaInfo :exec
UPDATE assets
SET duration_ms = $2,
    width = $3,
    height = $4,
    fps = $5,
    codec = $6,
    updated_by_user_id = $7,
    updated_at = now()
WHERE id = $1
`

type UpdateAssetMediaInfoParams struct {
	ID              pgtype.UUID    `json:"id"`
	DurationMs      pgtype.Int4    `json:"duration_ms"`
	Width           pgtype.Int4    `json:"width"`
	Height          pgtype.Int4    `json:"height"`
	Fps             pgtype.Numeric `json:"fps"`
	Codec           pgtype.Text    `json:"codec"`
	UpdatedByUserID pgtype.UUID    `json:"updated_by_user_id"`
}

func (q *Queries) UpdateAssetMediaInfo(ctx context.Context, arg UpdateAssetMediaInfoParams) error {
	_, err := q.db.Exec(ctx, updateAssetMediaInfo,
		arg.ID,
		arg.DurationMs,
		arg.Width,
		arg.Height,
		arg.Fps,
		arg.Codec,
		arg.UpdatedByUserID,
	)
	return err
}

const updateAssetStatus = `-- name: UpdateAssetStatus :exec
UPDATE assets
SET status = $2,
    updated_by_user_id = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateAssetStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	Status          string      `json:"status"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) error {
	_, err := q.db.Exec(ctx, updateAssetStatus, arg.ID, arg.Status, arg.UpdatedByUserID)
	return err
}
