// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation_tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGenerationTask = `-- name: CreateGenerationTask :one
INSERT INTO generation_tasks (
    product_id,
    created_by_user_id,
    task_type,
    status,
    variant_count,
    target_duration_ms,
    style_prompt,
    config_snapshot
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, product_id, created_by_user_id, task_type, status, variant_count, target_duration_ms, style_prompt, config_snapshot, error_message, created_at, updated_at, started_at, finished_at
`

type CreateGenerationTaskParams struct {
	ProductID        pgtype.UUID `json:"product_id"`
	CreatedByUserID  pgtype.UUID `json:"created_by_user_id"`
	TaskType         string      `json:"task_type"`
	Status           string      `json:"status"`
	VariantCount     int32       `json:"variant_count"`
	TargetDurationMs pgtype.Int4 `json:"target_duration_ms"`
	StylePrompt      pgtype.Text `json:"style_prompt"`
	ConfigSnapshot   []byte      `json:"config_snapshot"`
}

func (q *Queries) CreateGenerationTask(ctx context.Context, arg CreateGenerationTaskParams) (GenerationTask, error) {
	row := q.db.QueryRow(ctx, createGenerationTask,
		arg.ProductID,
		arg.CreatedByUserID,
		arg.TaskType,
		arg.Status,
		arg.VariantCount,
		arg.TargetDurationMs,
		arg.StylePrompt,
		arg.ConfigSnapshot,
	)
	var i GenerationTask
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CreatedByUserID,
		&i.TaskType,
		&i.Status,
		&i.VariantCount,
		&i.TargetDurationMs,
		&i.StylePrompt,
		&i.ConfigSnapshot,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getGenerationTaskByID = `-- name: GetGenerationTaskByID :one
SELECT id, product_id, created_by_user_id, task_type, status, variant_count, target_duration_ms, style_prompt, config_snapshot, error_message, created_at, updated_at, started_at, finished_at FROM generation_tasks
WHERE id = $1
`

func (q *Queries) GetGenerationTaskByID(ctx context.Context, id pgtype.UUID) (GenerationTask, error) {
	row := q.db.QueryRow(ctx, getGenerationTaskByID, id)
	var i GenerationTask
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.CreatedByUserID,
		&i.TaskType,
		&i.Status,
		&i.VariantCount,
		&i.TargetDurationMs,
		&i.StylePrompt,
		&i.ConfigSnapshot,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listGenerationTasks = `-- name: ListGenerationTasks :many
SELECT id, product_id, created_by_user_id, task_type, status, variant_count, target_duration_ms, style_prompt, config_snapshot, error_message, created_at, updated_at, started_at, finished_at FROM generation_tasks
WHERE status = COALESCE($1, status)
ORDER BY created_at DESC
`

func (q *Queries) ListGenerationTasks(ctx context.Context, status pgtype.Text) ([]GenerationTask, error) {
	rows, err := q.db.Query(ctx, listGenerationTasks, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationTask
	for rows.Next() {
		var i GenerationTask
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CreatedByUserID,
			&i.TaskType,
			&i.Status,
			&i.VariantCount,
			&i.TargetDurationMs,
			&i.StylePrompt,
			&i.ConfigSnapshot,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenerationTaskStatus = `-- name: UpdateGenerationTaskStatus :exec
UPDATE generation_tasks
SET status = $2,
    error_message = $3,
    updated_at = now(),
    started_at = CASE WHEN $2 = 'running' AND started_at IS NULL THEN now() ELSE started_at END,
    finished_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled') THEN now() ELSE finished_at END
WHERE id = $1
`

type UpdateGenerationTaskStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateGenerationTaskStatus(ctx context.Context, arg UpdateGenerationTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateGenerationTaskStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
