// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Asset struct {
	ID                      pgtype.UUID        `json:"id"`
	ProductID               pgtype.UUID        `json:"product_id"`
	StorageKey              string             `json:"storage_key"`
	FileName                string             `json:"file_name"`
	FileExt                 pgtype.Text        `json:"file_ext"`
	MimeType                pgtype.Text        `json:"mime_type"`
	FileSize                int64              `json:"file_size"`
	Checksum                pgtype.Text        `json:"checksum"`
	SourceType              string             `json:"source_type"`
	DurationMs              pgtype.Int4        `json:"duration_ms"`
	Width                   pgtype.Int4        `json:"width"`
	Height                  pgtype.Int4        `json:"height"`
	Fps                     pgtype.Numeric     `json:"fps"`
	Codec                   pgtype.Text        `json:"codec"`
	Status                  string             `json:"status"`
	ManualCleanStatus       string             `json:"manual_clean_status"`
	SourceOriginalName      pgtype.Text        `json:"source_original_name"`
	SourceInMs              pgtype.Int4        `json:"source_in_ms"`
	SourceOutMs             pgtype.Int4        `json:"source_out_ms"`
	Metadata                []byte             `json:"metadata"`
	CreatedByUserID         pgtype.UUID        `json:"created_by_user_id"`
	UpdatedByUserID         pgtype.UUID        `json:"updated_by_user_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	AssetName               pgtype.Text        `json:"asset_name"`
	SourcePath              pgtype.Text        `json:"source_path"`
	IngestionSource         string             `json:"ingestion_source"`
	AnalysisStatus          string             `json:"analysis_status"`
	UsabilityStatus         string             `json:"usability_status"`
	HasAudio                bool               `json:"has_audio"`
	AudioCodec              pgtype.Text        `json:"audio_codec"`
	BitrateKbps             pgtype.Int4        `json:"bitrate_kbps"`
	SceneDescription        pgtype.Text        `json:"scene_description"`
	ShotSize                pgtype.Text        `json:"shot_size"`
	CameraMovement          pgtype.Text        `json:"camera_movement"`
	Subjects                []byte             `json:"subjects"`
	SceneTags               []byte             `json:"scene_tags"`
	QualityTags             []byte             `json:"quality_tags"`
	ModelResult             []byte             `json:"model_result"`
	ReviewerNotes           pgtype.Text        `json:"reviewer_notes"`
	AnalysisError           pgtype.Text        `json:"analysis_error"`
	AnalyzedAt              pgtype.Timestamptz `json:"analyzed_at"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	ModelLabels             []byte             `json:"model_labels"`
	ReviewOverrides         []byte             `json:"review_overrides"`
	LikelyHasSpeech         bool               `json:"likely_has_speech"`
	Embedding               []byte             `json:"embedding"`
	DefaultUseOriginalAudio bool               `json:"default_use_original_audio"`
}

type AssetEmbeddingObject struct {
	ID           pgtype.UUID        `json:"id"`
	AssetID      pgtype.UUID        `json:"asset_id"`
	ObjectType   string             `json:"object_type"`
	ObjectID     pgtype.UUID        `json:"object_id"`
	Text         string             `json:"text"`
	TextHash     string             `json:"text_hash"`
	ProviderID   pgtype.UUID        `json:"provider_id"`
	Model        string             `json:"model"`
	Dimension    int32              `json:"dimension"`
	Embedding    pgvector.Vector    `json:"embedding"`
	Metadata     []byte             `json:"metadata"`
	Status       string             `json:"status"`
	ErrorMessage string             `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AssetFrameSnapshot struct {
	ID          pgtype.UUID        `json:"id"`
	AssetID     pgtype.UUID        `json:"asset_id"`
	FrameIndex  int32              `json:"frame_index"`
	TimestampMs int32              `json:"timestamp_ms"`
	StorageKey  string             `json:"storage_key"`
	Width       pgtype.Int4        `json:"width"`
	Height      pgtype.Int4        `json:"height"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AssetSellingPoint struct {
	AssetID        pgtype.UUID        `json:"asset_id"`
	SellingPointID pgtype.UUID        `json:"selling_point_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ClipSegment struct {
	ID                 pgtype.UUID        `json:"id"`
	EditPlanID         pgtype.UUID        `json:"edit_plan_id"`
	SegmentIndex       int32              `json:"segment_index"`
	NarrationSegmentID pgtype.UUID        `json:"narration_segment_id"`
	AssetID            pgtype.UUID        `json:"asset_id"`
	SpeechSegmentID    pgtype.UUID        `json:"speech_segment_id"`
	SourceInMs         int32              `json:"source_in_ms"`
	SourceOutMs        int32              `json:"source_out_ms"`
	TimelineInMs       int32              `json:"timeline_in_ms"`
	TimelineDurationMs int32              `json:"timeline_duration_ms"`
	SourceType         string             `json:"source_type"`
	Label              string             `json:"label"`
	VisualGoal         string             `json:"visual_goal"`
	UseOriginalAudio   bool               `json:"use_original_audio"`
	AudioGainDb        pgtype.Numeric     `json:"audio_gain_db"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type EditPlan struct {
	ID                pgtype.UUID        `json:"id"`
	GenerationRunID   pgtype.UUID        `json:"generation_run_id"`
	ScriptVariantID   pgtype.UUID        `json:"script_variant_id"`
	VoiceoverID       pgtype.UUID        `json:"voiceover_id"`
	Status            string             `json:"status"`
	CandidateSnapshot []byte             `json:"candidate_snapshot"`
	PlanJson          []byte             `json:"plan_json"`
	LlmProvider       string             `json:"llm_provider"`
	LlmModel          string             `json:"llm_model"`
	PromptVersion     string             `json:"prompt_version"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type GenerationRun struct {
	ID              pgtype.UUID        `json:"id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	VoiceoverTaskID pgtype.UUID        `json:"voiceover_task_id"`
	ScriptVariantID pgtype.UUID        `json:"script_variant_id"`
	VoiceoverID     pgtype.UUID        `json:"voiceover_id"`
	Status          string             `json:"status"`
	Stage           string             `json:"stage"`
	Progress        int32              `json:"progress"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	ConfigSnapshot  []byte             `json:"config_snapshot"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type GenerationRunTask struct {
	GenerationRunID  pgtype.UUID        `json:"generation_run_id"`
	GenerationTaskID pgtype.UUID        `json:"generation_task_id"`
	Stage            string             `json:"stage"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type GenerationTask struct {
	ID               pgtype.UUID        `json:"id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	CreatedByUserID  pgtype.UUID        `json:"created_by_user_id"`
	TaskType         string             `json:"task_type"`
	Status           string             `json:"status"`
	VariantCount     int32              `json:"variant_count"`
	TargetDurationMs pgtype.Int4        `json:"target_duration_ms"`
	StylePrompt      pgtype.Text        `json:"style_prompt"`
	ConfigSnapshot   []byte             `json:"config_snapshot"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	RetryCount       int32              `json:"retry_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

type ModelProvider struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	ProviderType string             `json:"provider_type"`
	BaseUrl      string             `json:"base_url"`
	ApiKey       string             `json:"api_key"`
	Enabled      bool               `json:"enabled"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type NarrationSegment struct {
	ID                 pgtype.UUID        `json:"id"`
	ScriptVariantID    pgtype.UUID        `json:"script_variant_id"`
	VoiceoverID        pgtype.UUID        `json:"voiceover_id"`
	SegmentIndex       int32              `json:"segment_index"`
	Text               string             `json:"text"`
	StartMs            int32              `json:"start_ms"`
	EndMs              int32              `json:"end_ms"`
	Confidence         pgtype.Numeric     `json:"confidence"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SynthesisUnitIndex pgtype.Int4        `json:"synthesis_unit_index"`
}

type Product struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	Category        pgtype.Text        `json:"category"`
	Status          string             `json:"status"`
	Metadata        []byte             `json:"metadata"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	UpdatedByUserID pgtype.UUID        `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProductSellingPoint struct {
	ID              pgtype.UUID        `json:"id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Priority        int32              `json:"priority"`
	Status          string             `json:"status"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	UpdatedByUserID pgtype.UUID        `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ScriptVariant struct {
	ID                       pgtype.UUID        `json:"id"`
	GenerationTaskID         pgtype.UUID        `json:"generation_task_id"`
	ProductID                pgtype.UUID        `json:"product_id"`
	VariantIndex             int32              `json:"variant_index"`
	Hook                     string             `json:"hook"`
	ScriptText               string             `json:"script_text"`
	EditingIntent            string             `json:"editing_intent"`
	Beats                    []byte             `json:"beats"`
	VoiceProfileID           pgtype.UUID        `json:"voice_profile_id"`
	VoiceProfileName         string             `json:"voice_profile_name"`
	ReferenceAudioStorageKey string             `json:"reference_audio_storage_key"`
	ReferenceAudioFileName   string             `json:"reference_audio_file_name"`
	ReferenceText            string             `json:"reference_text"`
	Status                   string             `json:"status"`
	ErrorMessage             pgtype.Text        `json:"error_message"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type SpeechSegment struct {
	ID              pgtype.UUID        `json:"id"`
	AssetID         pgtype.UUID        `json:"asset_id"`
	StartMs         int32              `json:"start_ms"`
	EndMs           int32              `json:"end_ms"`
	Transcript      string             `json:"transcript"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Source          string             `json:"source"`
	Status          string             `json:"status"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	UpdatedByUserID pgtype.UUID        `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type SystemConfig struct {
	ID              pgtype.UUID        `json:"id"`
	ConfigKey       string             `json:"config_key"`
	ConfigValue     []byte             `json:"config_value"`
	ConfigType      string             `json:"config_type"`
	IsSecret        bool               `json:"is_secret"`
	Description     pgtype.Text        `json:"description"`
	UpdatedByUserID pgtype.UUID        `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UploadToken struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	Status    string             `json:"status"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	DisplayName  string             `json:"display_name"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type VoiceAudition struct {
	ID                       pgtype.UUID        `json:"id"`
	GenerationTaskID         pgtype.UUID        `json:"generation_task_id"`
	VoiceProfileID           pgtype.UUID        `json:"voice_profile_id"`
	VoiceProfileName         string             `json:"voice_profile_name"`
	ReferenceAudioStorageKey string             `json:"reference_audio_storage_key"`
	ReferenceAudioFileName   string             `json:"reference_audio_file_name"`
	ReferenceText            string             `json:"reference_text"`
	Text                     string             `json:"text"`
	AudioStorageKey          pgtype.Text        `json:"audio_storage_key"`
	SampleRate               pgtype.Int4        `json:"sample_rate"`
	DurationMs               pgtype.Int4        `json:"duration_ms"`
	Status                   string             `json:"status"`
	ErrorMessage             pgtype.Text        `json:"error_message"`
	CreatedByUserID          pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type VoiceProfile struct {
	ID                       pgtype.UUID        `json:"id"`
	Name                     string             `json:"name"`
	Language                 string             `json:"language"`
	StyleTags                []byte             `json:"style_tags"`
	ReferenceText            string             `json:"reference_text"`
	ReferenceAudioStorageKey string             `json:"reference_audio_storage_key"`
	ReferenceAudioFileName   string             `json:"reference_audio_file_name"`
	ReferenceAudioMimeType   string             `json:"reference_audio_mime_type"`
	ReferenceAudioSize       int64              `json:"reference_audio_size"`
	PreviewText              string             `json:"preview_text"`
	PreviewAudioStorageKey   pgtype.Text        `json:"preview_audio_storage_key"`
	PreviewStatus            string             `json:"preview_status"`
	PreviewError             pgtype.Text        `json:"preview_error"`
	Status                   string             `json:"status"`
	IsDefault                bool               `json:"is_default"`
	CreatedByUserID          pgtype.UUID        `json:"created_by_user_id"`
	UpdatedByUserID          pgtype.UUID        `json:"updated_by_user_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type Voiceover struct {
	ID              pgtype.UUID        `json:"id"`
	ScriptVariantID pgtype.UUID        `json:"script_variant_id"`
	StorageKey      pgtype.Text        `json:"storage_key"`
	VoiceProvider   string             `json:"voice_provider"`
	VoiceModel      string             `json:"voice_model"`
	VoiceName       string             `json:"voice_name"`
	SampleRate      pgtype.Int4        `json:"sample_rate"`
	DurationMs      pgtype.Int4        `json:"duration_ms"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
