// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID                 pgtype.UUID        `json:"id"`
	ProductID          pgtype.UUID        `json:"product_id"`
	StorageKey         string             `json:"storage_key"`
	FileName           string             `json:"file_name"`
	FileExt            pgtype.Text        `json:"file_ext"`
	MimeType           pgtype.Text        `json:"mime_type"`
	FileSize           int64              `json:"file_size"`
	Checksum           pgtype.Text        `json:"checksum"`
	SourceType         string             `json:"source_type"`
	DurationMs         pgtype.Int4        `json:"duration_ms"`
	Width              pgtype.Int4        `json:"width"`
	Height             pgtype.Int4        `json:"height"`
	Fps                pgtype.Numeric     `json:"fps"`
	Codec              pgtype.Text        `json:"codec"`
	Status             string             `json:"status"`
	ManualCleanStatus  string             `json:"manual_clean_status"`
	SourceOriginalName pgtype.Text        `json:"source_original_name"`
	SourceInMs         pgtype.Int4        `json:"source_in_ms"`
	SourceOutMs        pgtype.Int4        `json:"source_out_ms"`
	Metadata           []byte             `json:"metadata"`
	CreatedByUserID    pgtype.UUID        `json:"created_by_user_id"`
	UpdatedByUserID    pgtype.UUID        `json:"updated_by_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type GenerationTask struct {
	ID               pgtype.UUID        `json:"id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	CreatedByUserID  pgtype.UUID        `json:"created_by_user_id"`
	TaskType         string             `json:"task_type"`
	Status           string             `json:"status"`
	VariantCount     int32              `json:"variant_count"`
	TargetDurationMs pgtype.Int4        `json:"target_duration_ms"`
	StylePrompt      pgtype.Text        `json:"style_prompt"`
	ConfigSnapshot   []byte             `json:"config_snapshot"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

type Product struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	Category        pgtype.Text        `json:"category"`
	Status          string             `json:"status"`
	Metadata        []byte             `json:"metadata"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	UpdatedByUserID pgtype.UUID        `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProductSellingPoint struct {
	ID              pgtype.UUID        `json:"id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Priority        int32              `json:"priority"`
	Status          string             `json:"status"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	UpdatedByUserID pgtype.UUID        `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type SystemConfig struct {
	ID              pgtype.UUID        `json:"id"`
	ConfigKey       string             `json:"config_key"`
	ConfigValue     []byte             `json:"config_value"`
	ConfigType      string             `json:"config_type"`
	IsSecret        bool               `json:"is_secret"`
	Description     pgtype.Text        `json:"description"`
	UpdatedByUserID pgtype.UUID        `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UploadToken struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	Status    string             `json:"status"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	DisplayName  string             `json:"display_name"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
