// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProduct = `-- name: ArchiveProduct :exec
UPDATE products
SET status = 'archived',
    updated_by_user_id = $2,
    updated_at = now()
WHERE id = $1
`

type ArchiveProductParams struct {
	ID              pgtype.UUID `json:"id"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) ArchiveProduct(ctx context.Context, arg ArchiveProductParams) error {
	_, err := q.db.Exec(ctx, archiveProduct, arg.ID, arg.UpdatedByUserID)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    description,
    category,
    status,
    metadata,
    created_by_user_id,
    updated_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $6
)
RETURNING id, name, description, category, status, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type CreateProductParams struct {
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	Category        pgtype.Text `json:"category"`
	Status          string      `json:"status"`
	Metadata        []byte      `json:"metadata"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Status,
		arg.Metadata,
		arg.CreatedByUserID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.Metadata,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, category, status, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.Metadata,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, category, status, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at FROM products
WHERE status = COALESCE($1, status)
ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context, status pgtype.Text) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Status,
			&i.Metadata,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2,
    description = $3,
    category = $4,
    metadata = $5,
    updated_by_user_id = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, category, status, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type UpdateProductParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	Category        pgtype.Text `json:"category"`
	Metadata        []byte      `json:"metadata"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Metadata,
		arg.UpdatedByUserID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Status,
		&i.Metadata,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
