// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddAssetSellingPoint(ctx context.Context, arg AddAssetSellingPointParams) error
	ArchiveAsset(ctx context.Context, arg ArchiveAssetParams) error
	ArchiveProduct(ctx context.Context, arg ArchiveProductParams) error
	ArchiveSellingPoint(ctx context.Context, arg ArchiveSellingPointParams) error
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateGenerationTask(ctx context.Context, arg CreateGenerationTaskParams) (GenerationTask, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSellingPoint(ctx context.Context, arg CreateSellingPointParams) (ProductSellingPoint, error)
	CreateSpeechSegment(ctx context.Context, arg CreateSpeechSegmentParams) (SpeechSegment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error)
	GetGenerationTaskByID(ctx context.Context, id pgtype.UUID) (GenerationTask, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	GetSellingPointByID(ctx context.Context, id pgtype.UUID) (ProductSellingPoint, error)
	GetSystemConfigByKey(ctx context.Context, configKey string) (SystemConfig, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error)
	ListGenerationTasks(ctx context.Context, status pgtype.Text) ([]GenerationTask, error)
	ListProducts(ctx context.Context, status pgtype.Text) ([]Product, error)
	ListSellingPointIDsByAsset(ctx context.Context, assetID pgtype.UUID) ([]pgtype.UUID, error)
	ListSellingPointsByProduct(ctx context.Context, arg ListSellingPointsByProductParams) ([]ProductSellingPoint, error)
	ListSpeechSegmentsByAsset(ctx context.Context, arg ListSpeechSegmentsByAssetParams) ([]SpeechSegment, error)
	ListSystemConfigs(ctx context.Context) ([]SystemConfig, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveAssetSellingPoint(ctx context.Context, arg RemoveAssetSellingPointParams) error
	UpdateAssetAnalysis(ctx context.Context, arg UpdateAssetAnalysisParams) error
	UpdateAssetMediaInfo(ctx context.Context, arg UpdateAssetMediaInfoParams) error
	UpdateAssetReview(ctx context.Context, arg UpdateAssetReviewParams) error
	UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) error
	UpdateGenerationTaskStatus(ctx context.Context, arg UpdateGenerationTaskStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSellingPoint(ctx context.Context, arg UpdateSellingPointParams) (ProductSellingPoint, error)
	UpdateSpeechSegment(ctx context.Context, arg UpdateSpeechSegmentParams) (SpeechSegment, error)
	UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) (SystemConfig, error)
}

var _ Querier = (*Queries)(nil)
