// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveProduct(ctx context.Context, arg ArchiveProductParams) error
	ArchiveSellingPoint(ctx context.Context, arg ArchiveSellingPointParams) error
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateGenerationTask(ctx context.Context, arg CreateGenerationTaskParams) (GenerationTask, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSellingPoint(ctx context.Context, arg CreateSellingPointParams) (ProductSellingPoint, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error)
	GetGenerationTaskByID(ctx context.Context, id pgtype.UUID) (GenerationTask, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	GetSellingPointByID(ctx context.Context, id pgtype.UUID) (ProductSellingPoint, error)
	GetSystemConfigByKey(ctx context.Context, configKey string) (SystemConfig, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error)
	ListGenerationTasks(ctx context.Context, status pgtype.Text) ([]GenerationTask, error)
	ListProducts(ctx context.Context, status pgtype.Text) ([]Product, error)
	ListSellingPointsByProduct(ctx context.Context, arg ListSellingPointsByProductParams) ([]ProductSellingPoint, error)
	ListSystemConfigs(ctx context.Context) ([]SystemConfig, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAssetMediaInfo(ctx context.Context, arg UpdateAssetMediaInfoParams) error
	UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) error
	UpdateGenerationTaskStatus(ctx context.Context, arg UpdateGenerationTaskStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSellingPoint(ctx context.Context, arg UpdateSellingPointParams) (ProductSellingPoint, error)
	UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) (SystemConfig, error)
}

var _ Querier = (*Queries)(nil)
