// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: selling_points.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveSellingPoint = `-- name: ArchiveSellingPoint :exec
UPDATE product_selling_points
SET status = 'archived',
    updated_by_user_id = $2,
    updated_at = now()
WHERE id = $1
`

type ArchiveSellingPointParams struct {
	ID              pgtype.UUID `json:"id"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) ArchiveSellingPoint(ctx context.Context, arg ArchiveSellingPointParams) error {
	_, err := q.db.Exec(ctx, archiveSellingPoint, arg.ID, arg.UpdatedByUserID)
	return err
}

const countAssetSellingPointLinks = `-- name: CountAssetSellingPointLinks :one
SELECT COUNT(*)::int
FROM asset_selling_points
WHERE selling_point_id = $1
`

func (q *Queries) CountAssetSellingPointLinks(ctx context.Context, sellingPointID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countAssetSellingPointLinks, sellingPointID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSellingPoint = `-- name: CreateSellingPoint :one
INSERT INTO product_selling_points (
    product_id,
    title,
    description,
    priority,
    status,
    created_by_user_id,
    updated_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $6
)
RETURNING id, product_id, title, description, priority, status, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type CreateSellingPointParams struct {
	ProductID       pgtype.UUID `json:"product_id"`
	Title           string      `json:"title"`
	Description     pgtype.Text `json:"description"`
	Priority        int32       `json:"priority"`
	Status          string      `json:"status"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateSellingPoint(ctx context.Context, arg CreateSellingPointParams) (ProductSellingPoint, error) {
	row := q.db.QueryRow(ctx, createSellingPoint,
		arg.ProductID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.CreatedByUserID,
	)
	var i ProductSellingPoint
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSellingPoint = `-- name: DeleteSellingPoint :exec
DELETE FROM product_selling_points
WHERE id = $1
`

func (q *Queries) DeleteSellingPoint(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSellingPoint, id)
	return err
}

const getSellingPointByID = `-- name: GetSellingPointByID :one
SELECT id, product_id, title, description, priority, status, created_by_user_id, updated_by_user_id, created_at, updated_at FROM product_selling_points
WHERE id = $1
`

func (q *Queries) GetSellingPointByID(ctx context.Context, id pgtype.UUID) (ProductSellingPoint, error) {
	row := q.db.QueryRow(ctx, getSellingPointByID, id)
	var i ProductSellingPoint
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSellingPointsByProduct = `-- name: ListSellingPointsByProduct :many
SELECT id, product_id, title, description, priority, status, created_by_user_id, updated_by_user_id, created_at, updated_at FROM product_selling_points
WHERE product_id = $1
  AND status = COALESCE($2, status)
ORDER BY priority DESC, created_at DESC
`

type ListSellingPointsByProductParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Status    pgtype.Text `json:"status"`
}

func (q *Queries) ListSellingPointsByProduct(ctx context.Context, arg ListSellingPointsByProductParams) ([]ProductSellingPoint, error) {
	rows, err := q.db.Query(ctx, listSellingPointsByProduct, arg.ProductID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductSellingPoint
	for rows.Next() {
		var i ProductSellingPoint
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSellingPoint = `-- name: UpdateSellingPoint :one
UPDATE product_selling_points
SET title = $2,
    description = $3,
    priority = $4,
    updated_by_user_id = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, title, description, priority, status, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type UpdateSellingPointParams struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Description     pgtype.Text `json:"description"`
	Priority        int32       `json:"priority"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) UpdateSellingPoint(ctx context.Context, arg UpdateSellingPointParams) (ProductSellingPoint, error) {
	row := q.db.QueryRow(ctx, updateSellingPoint,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.UpdatedByUserID,
	)
	var i ProductSellingPoint
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
