// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: speech_segments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpeechSegment = `-- name: CreateSpeechSegment :one
INSERT INTO speech_segments (
    asset_id,
    start_ms,
    end_ms,
    transcript,
    confidence,
    source,
    status,
    created_by_user_id,
    updated_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8
)
RETURNING id, asset_id, start_ms, end_ms, transcript, confidence, source, status, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type CreateSpeechSegmentParams struct {
	AssetID         pgtype.UUID    `json:"asset_id"`
	StartMs         int32          `json:"start_ms"`
	EndMs           int32          `json:"end_ms"`
	Transcript      string         `json:"transcript"`
	Confidence      pgtype.Numeric `json:"confidence"`
	Source          string         `json:"source"`
	Status          string         `json:"status"`
	CreatedByUserID pgtype.UUID    `json:"created_by_user_id"`
}

func (q *Queries) CreateSpeechSegment(ctx context.Context, arg CreateSpeechSegmentParams) (SpeechSegment, error) {
	row := q.db.QueryRow(ctx, createSpeechSegment,
		arg.AssetID,
		arg.StartMs,
		arg.EndMs,
		arg.Transcript,
		arg.Confidence,
		arg.Source,
		arg.Status,
		arg.CreatedByUserID,
	)
	var i SpeechSegment
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.StartMs,
		&i.EndMs,
		&i.Transcript,
		&i.Confidence,
		&i.Source,
		&i.Status,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpeechSegmentsByAsset = `-- name: ListSpeechSegmentsByAsset :many
SELECT id, asset_id, start_ms, end_ms, transcript, confidence, source, status, created_by_user_id, updated_by_user_id, created_at, updated_at FROM speech_segments
WHERE asset_id = $1
  AND status = COALESCE($2, status)
ORDER BY start_ms ASC, created_at ASC
`

type ListSpeechSegmentsByAssetParams struct {
	AssetID pgtype.UUID `json:"asset_id"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) ListSpeechSegmentsByAsset(ctx context.Context, arg ListSpeechSegmentsByAssetParams) ([]SpeechSegment, error) {
	rows, err := q.db.Query(ctx, listSpeechSegmentsByAsset, arg.AssetID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpeechSegment
	for rows.Next() {
		var i SpeechSegment
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.StartMs,
			&i.EndMs,
			&i.Transcript,
			&i.Confidence,
			&i.Source,
			&i.Status,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpeechSegment = `-- name: UpdateSpeechSegment :one
UPDATE speech_segments
SET start_ms = $2,
    end_ms = $3,
    transcript = $4,
    confidence = $5,
    source = $6,
    status = $7,
    updated_by_user_id = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, asset_id, start_ms, end_ms, transcript, confidence, source, status, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type UpdateSpeechSegmentParams struct {
	ID              pgtype.UUID    `json:"id"`
	StartMs         int32          `json:"start_ms"`
	EndMs           int32          `json:"end_ms"`
	Transcript      string         `json:"transcript"`
	Confidence      pgtype.Numeric `json:"confidence"`
	Source          string         `json:"source"`
	Status          string         `json:"status"`
	UpdatedByUserID pgtype.UUID    `json:"updated_by_user_id"`
}

func (q *Queries) UpdateSpeechSegment(ctx context.Context, arg UpdateSpeechSegmentParams) (SpeechSegment, error) {
	row := q.db.QueryRow(ctx, updateSpeechSegment,
		arg.ID,
		arg.StartMs,
		arg.EndMs,
		arg.Transcript,
		arg.Confidence,
		arg.Source,
		arg.Status,
		arg.UpdatedByUserID,
	)
	var i SpeechSegment
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.StartMs,
		&i.EndMs,
		&i.Transcript,
		&i.Confidence,
		&i.Source,
		&i.Status,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
