// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: system_configs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSystemConfigByKey = `-- name: GetSystemConfigByKey :one
SELECT id, config_key, config_value, config_type, is_secret, description, updated_by_user_id, created_at, updated_at FROM system_configs
WHERE config_key = $1
`

func (q *Queries) GetSystemConfigByKey(ctx context.Context, configKey string) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, getSystemConfigByKey, configKey)
	var i SystemConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.ConfigType,
		&i.IsSecret,
		&i.Description,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemConfigs = `-- name: ListSystemConfigs :many
SELECT id, config_key, config_value, config_type, is_secret, description, updated_by_user_id, created_at, updated_at FROM system_configs
ORDER BY config_key ASC
`

func (q *Queries) ListSystemConfigs(ctx context.Context) ([]SystemConfig, error) {
	rows, err := q.db.Query(ctx, listSystemConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemConfig
	for rows.Next() {
		var i SystemConfig
		if err := rows.Scan(
			&i.ID,
			&i.ConfigKey,
			&i.ConfigValue,
			&i.ConfigType,
			&i.IsSecret,
			&i.Description,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemConfig = `-- name: UpsertSystemConfig :one
INSERT INTO system_configs (
    config_key,
    config_value,
    config_type,
    is_secret,
    description,
    updated_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (config_key) DO UPDATE SET
    config_value = EXCLUDED.config_value,
    config_type = EXCLUDED.config_type,
    is_secret = EXCLUDED.is_secret,
    description = EXCLUDED.description,
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    updated_at = now()
RETURNING id, config_key, config_value, config_type, is_secret, description, updated_by_user_id, created_at, updated_at
`

type UpsertSystemConfigParams struct {
	ConfigKey       string      `json:"config_key"`
	ConfigValue     []byte      `json:"config_value"`
	ConfigType      string      `json:"config_type"`
	IsSecret        bool        `json:"is_secret"`
	Description     pgtype.Text `json:"description"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, upsertSystemConfig,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.ConfigType,
		arg.IsSecret,
		arg.Description,
		arg.UpdatedByUserID,
	)
	var i SystemConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.ConfigType,
		&i.IsSecret,
		&i.Description,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
