// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: voiceover_pipeline.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNarrationSegment = `-- name: CreateNarrationSegment :one
INSERT INTO narration_segments (
    script_variant_id,
    voiceover_id,
    segment_index,
    text,
    start_ms,
    end_ms,
    confidence
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, script_variant_id, voiceover_id, segment_index, text, start_ms, end_ms, confidence, created_at, updated_at
`

type CreateNarrationSegmentParams struct {
	ScriptVariantID pgtype.UUID    `json:"script_variant_id"`
	VoiceoverID     pgtype.UUID    `json:"voiceover_id"`
	SegmentIndex    int32          `json:"segment_index"`
	Text            string         `json:"text"`
	StartMs         int32          `json:"start_ms"`
	EndMs           int32          `json:"end_ms"`
	Confidence      pgtype.Numeric `json:"confidence"`
}

func (q *Queries) CreateNarrationSegment(ctx context.Context, arg CreateNarrationSegmentParams) (NarrationSegment, error) {
	row := q.db.QueryRow(ctx, createNarrationSegment,
		arg.ScriptVariantID,
		arg.VoiceoverID,
		arg.SegmentIndex,
		arg.Text,
		arg.StartMs,
		arg.EndMs,
		arg.Confidence,
	)
	var i NarrationSegment
	err := row.Scan(
		&i.ID,
		&i.ScriptVariantID,
		&i.VoiceoverID,
		&i.SegmentIndex,
		&i.Text,
		&i.StartMs,
		&i.EndMs,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScriptVariant = `-- name: CreateScriptVariant :one
INSERT INTO script_variants (
    generation_task_id,
    product_id,
    variant_index,
    hook,
    script_text,
    editing_intent,
    beats,
    voice_profile_id,
    voice_profile_name,
    reference_audio_storage_key,
    reference_audio_file_name,
    reference_text
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, generation_task_id, product_id, variant_index, hook, script_text, editing_intent, beats, voice_profile_id, voice_profile_name, reference_audio_storage_key, reference_audio_file_name, reference_text, status, error_message, created_at, updated_at
`

type CreateScriptVariantParams struct {
	GenerationTaskID         pgtype.UUID `json:"generation_task_id"`
	ProductID                pgtype.UUID `json:"product_id"`
	VariantIndex             int32       `json:"variant_index"`
	Hook                     string      `json:"hook"`
	ScriptText               string      `json:"script_text"`
	EditingIntent            string      `json:"editing_intent"`
	Beats                    []byte      `json:"beats"`
	VoiceProfileID           pgtype.UUID `json:"voice_profile_id"`
	VoiceProfileName         string      `json:"voice_profile_name"`
	ReferenceAudioStorageKey string      `json:"reference_audio_storage_key"`
	ReferenceAudioFileName   string      `json:"reference_audio_file_name"`
	ReferenceText            string      `json:"reference_text"`
}

func (q *Queries) CreateScriptVariant(ctx context.Context, arg CreateScriptVariantParams) (ScriptVariant, error) {
	row := q.db.QueryRow(ctx, createScriptVariant,
		arg.GenerationTaskID,
		arg.ProductID,
		arg.VariantIndex,
		arg.Hook,
		arg.ScriptText,
		arg.EditingIntent,
		arg.Beats,
		arg.VoiceProfileID,
		arg.VoiceProfileName,
		arg.ReferenceAudioStorageKey,
		arg.ReferenceAudioFileName,
		arg.ReferenceText,
	)
	var i ScriptVariant
	err := row.Scan(
		&i.ID,
		&i.GenerationTaskID,
		&i.ProductID,
		&i.VariantIndex,
		&i.Hook,
		&i.ScriptText,
		&i.EditingIntent,
		&i.Beats,
		&i.VoiceProfileID,
		&i.VoiceProfileName,
		&i.ReferenceAudioStorageKey,
		&i.ReferenceAudioFileName,
		&i.ReferenceText,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoiceAudition = `-- name: CreateVoiceAudition :one
INSERT INTO voice_auditions (
    generation_task_id,
    voice_profile_id,
    voice_profile_name,
    reference_audio_storage_key,
    reference_audio_file_name,
    reference_text,
    text,
    created_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, generation_task_id, voice_profile_id, voice_profile_name, reference_audio_storage_key, reference_audio_file_name, reference_text, text, audio_storage_key, sample_rate, duration_ms, status, error_message, created_by_user_id, created_at, updated_at
`

type CreateVoiceAuditionParams struct {
	GenerationTaskID         pgtype.UUID `json:"generation_task_id"`
	VoiceProfileID           pgtype.UUID `json:"voice_profile_id"`
	VoiceProfileName         string      `json:"voice_profile_name"`
	ReferenceAudioStorageKey string      `json:"reference_audio_storage_key"`
	ReferenceAudioFileName   string      `json:"reference_audio_file_name"`
	ReferenceText            string      `json:"reference_text"`
	Text                     string      `json:"text"`
	CreatedByUserID          pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateVoiceAudition(ctx context.Context, arg CreateVoiceAuditionParams) (VoiceAudition, error) {
	row := q.db.QueryRow(ctx, createVoiceAudition,
		arg.GenerationTaskID,
		arg.VoiceProfileID,
		arg.VoiceProfileName,
		arg.ReferenceAudioStorageKey,
		arg.ReferenceAudioFileName,
		arg.ReferenceText,
		arg.Text,
		arg.CreatedByUserID,
	)
	var i VoiceAudition
	err := row.Scan(
		&i.ID,
		&i.GenerationTaskID,
		&i.VoiceProfileID,
		&i.VoiceProfileName,
		&i.ReferenceAudioStorageKey,
		&i.ReferenceAudioFileName,
		&i.ReferenceText,
		&i.Text,
		&i.AudioStorageKey,
		&i.SampleRate,
		&i.DurationMs,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoiceover = `-- name: CreateVoiceover :one
INSERT INTO voiceovers (
    script_variant_id,
    voice_provider,
    voice_model,
    voice_name
) VALUES ($1, $2, $3, $4)
RETURNING id, script_variant_id, storage_key, voice_provider, voice_model, voice_name, sample_rate, duration_ms, status, error_message, created_at, updated_at
`

type CreateVoiceoverParams struct {
	ScriptVariantID pgtype.UUID `json:"script_variant_id"`
	VoiceProvider   string      `json:"voice_provider"`
	VoiceModel      string      `json:"voice_model"`
	VoiceName       string      `json:"voice_name"`
}

func (q *Queries) CreateVoiceover(ctx context.Context, arg CreateVoiceoverParams) (Voiceover, error) {
	row := q.db.QueryRow(ctx, createVoiceover,
		arg.ScriptVariantID,
		arg.VoiceProvider,
		arg.VoiceModel,
		arg.VoiceName,
	)
	var i Voiceover
	err := row.Scan(
		&i.ID,
		&i.ScriptVariantID,
		&i.StorageKey,
		&i.VoiceProvider,
		&i.VoiceModel,
		&i.VoiceName,
		&i.SampleRate,
		&i.DurationMs,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNarrationSegmentsByVoiceoverID = `-- name: DeleteNarrationSegmentsByVoiceoverID :exec
DELETE FROM narration_segments
WHERE voiceover_id = $1
`

func (q *Queries) DeleteNarrationSegmentsByVoiceoverID(ctx context.Context, voiceoverID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNarrationSegmentsByVoiceoverID, voiceoverID)
	return err
}

const getScriptVariantByGenerationTaskID = `-- name: GetScriptVariantByGenerationTaskID :one
SELECT id, generation_task_id, product_id, variant_index, hook, script_text, editing_intent, beats, voice_profile_id, voice_profile_name, reference_audio_storage_key, reference_audio_file_name, reference_text, status, error_message, created_at, updated_at FROM script_variants
WHERE generation_task_id = $1
`

func (q *Queries) GetScriptVariantByGenerationTaskID(ctx context.Context, generationTaskID pgtype.UUID) (ScriptVariant, error) {
	row := q.db.QueryRow(ctx, getScriptVariantByGenerationTaskID, generationTaskID)
	var i ScriptVariant
	err := row.Scan(
		&i.ID,
		&i.GenerationTaskID,
		&i.ProductID,
		&i.VariantIndex,
		&i.Hook,
		&i.ScriptText,
		&i.EditingIntent,
		&i.Beats,
		&i.VoiceProfileID,
		&i.VoiceProfileName,
		&i.ReferenceAudioStorageKey,
		&i.ReferenceAudioFileName,
		&i.ReferenceText,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScriptVariantByID = `-- name: GetScriptVariantByID :one
SELECT id, generation_task_id, product_id, variant_index, hook, script_text, editing_intent, beats, voice_profile_id, voice_profile_name, reference_audio_storage_key, reference_audio_file_name, reference_text, status, error_message, created_at, updated_at FROM script_variants
WHERE id = $1
`

func (q *Queries) GetScriptVariantByID(ctx context.Context, id pgtype.UUID) (ScriptVariant, error) {
	row := q.db.QueryRow(ctx, getScriptVariantByID, id)
	var i ScriptVariant
	err := row.Scan(
		&i.ID,
		&i.GenerationTaskID,
		&i.ProductID,
		&i.VariantIndex,
		&i.Hook,
		&i.ScriptText,
		&i.EditingIntent,
		&i.Beats,
		&i.VoiceProfileID,
		&i.VoiceProfileName,
		&i.ReferenceAudioStorageKey,
		&i.ReferenceAudioFileName,
		&i.ReferenceText,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceAuditionByID = `-- name: GetVoiceAuditionByID :one
SELECT id, generation_task_id, voice_profile_id, voice_profile_name, reference_audio_storage_key, reference_audio_file_name, reference_text, text, audio_storage_key, sample_rate, duration_ms, status, error_message, created_by_user_id, created_at, updated_at FROM voice_auditions
WHERE id = $1
`

func (q *Queries) GetVoiceAuditionByID(ctx context.Context, id pgtype.UUID) (VoiceAudition, error) {
	row := q.db.QueryRow(ctx, getVoiceAuditionByID, id)
	var i VoiceAudition
	err := row.Scan(
		&i.ID,
		&i.GenerationTaskID,
		&i.VoiceProfileID,
		&i.VoiceProfileName,
		&i.ReferenceAudioStorageKey,
		&i.ReferenceAudioFileName,
		&i.ReferenceText,
		&i.Text,
		&i.AudioStorageKey,
		&i.SampleRate,
		&i.DurationMs,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceoverByID = `-- name: GetVoiceoverByID :one
SELECT id, script_variant_id, storage_key, voice_provider, voice_model, voice_name, sample_rate, duration_ms, status, error_message, created_at, updated_at FROM voiceovers
WHERE id = $1
`

func (q *Queries) GetVoiceoverByID(ctx context.Context, id pgtype.UUID) (Voiceover, error) {
	row := q.db.QueryRow(ctx, getVoiceoverByID, id)
	var i Voiceover
	err := row.Scan(
		&i.ID,
		&i.ScriptVariantID,
		&i.StorageKey,
		&i.VoiceProvider,
		&i.VoiceModel,
		&i.VoiceName,
		&i.SampleRate,
		&i.DurationMs,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceoverByScriptVariantID = `-- name: GetVoiceoverByScriptVariantID :one
SELECT id, script_variant_id, storage_key, voice_provider, voice_model, voice_name, sample_rate, duration_ms, status, error_message, created_at, updated_at FROM voiceovers
WHERE script_variant_id = $1
`

func (q *Queries) GetVoiceoverByScriptVariantID(ctx context.Context, scriptVariantID pgtype.UUID) (Voiceover, error) {
	row := q.db.QueryRow(ctx, getVoiceoverByScriptVariantID, scriptVariantID)
	var i Voiceover
	err := row.Scan(
		&i.ID,
		&i.ScriptVariantID,
		&i.StorageKey,
		&i.VoiceProvider,
		&i.VoiceModel,
		&i.VoiceName,
		&i.SampleRate,
		&i.DurationMs,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNarrationSegmentsByVoiceoverID = `-- name: ListNarrationSegmentsByVoiceoverID :many
SELECT id, script_variant_id, voiceover_id, segment_index, text, start_ms, end_ms, confidence, created_at, updated_at FROM narration_segments
WHERE voiceover_id = $1
ORDER BY segment_index ASC
`

func (q *Queries) ListNarrationSegmentsByVoiceoverID(ctx context.Context, voiceoverID pgtype.UUID) ([]NarrationSegment, error) {
	rows, err := q.db.Query(ctx, listNarrationSegmentsByVoiceoverID, voiceoverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NarrationSegment
	for rows.Next() {
		var i NarrationSegment
		if err := rows.Scan(
			&i.ID,
			&i.ScriptVariantID,
			&i.VoiceoverID,
			&i.SegmentIndex,
			&i.Text,
			&i.StartMs,
			&i.EndMs,
			&i.Confidence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScriptVariantsByGenerationTaskID = `-- name: ListScriptVariantsByGenerationTaskID :many
SELECT id, generation_task_id, product_id, variant_index, hook, script_text, editing_intent, beats, voice_profile_id, voice_profile_name, reference_audio_storage_key, reference_audio_file_name, reference_text, status, error_message, created_at, updated_at FROM script_variants
WHERE generation_task_id = $1
ORDER BY variant_index ASC
`

func (q *Queries) ListScriptVariantsByGenerationTaskID(ctx context.Context, generationTaskID pgtype.UUID) ([]ScriptVariant, error) {
	rows, err := q.db.Query(ctx, listScriptVariantsByGenerationTaskID, generationTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScriptVariant
	for rows.Next() {
		var i ScriptVariant
		if err := rows.Scan(
			&i.ID,
			&i.GenerationTaskID,
			&i.ProductID,
			&i.VariantIndex,
			&i.Hook,
			&i.ScriptText,
			&i.EditingIntent,
			&i.Beats,
			&i.VoiceProfileID,
			&i.VoiceProfileName,
			&i.ReferenceAudioStorageKey,
			&i.ReferenceAudioFileName,
			&i.ReferenceText,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoiceoverGenerationTasks = `-- name: ListVoiceoverGenerationTasks :many
SELECT id, product_id, created_by_user_id, task_type, status, variant_count, target_duration_ms, style_prompt, config_snapshot, error_message, retry_count, created_at, updated_at, started_at, finished_at FROM generation_tasks
WHERE task_type = 'voiceover_generate'
ORDER BY created_at DESC
`

func (q *Queries) ListVoiceoverGenerationTasks(ctx context.Context) ([]GenerationTask, error) {
	rows, err := q.db.Query(ctx, listVoiceoverGenerationTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationTask
	for rows.Next() {
		var i GenerationTask
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CreatedByUserID,
			&i.TaskType,
			&i.Status,
			&i.VariantCount,
			&i.TargetDurationMs,
			&i.StylePrompt,
			&i.ConfigSnapshot,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScriptVariantFailed = `-- name: MarkScriptVariantFailed :exec
UPDATE script_variants
SET status = 'failed', error_message = $2, updated_at = now()
WHERE id = $1
`

type MarkScriptVariantFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkScriptVariantFailed(ctx context.Context, arg MarkScriptVariantFailedParams) error {
	_, err := q.db.Exec(ctx, markScriptVariantFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markScriptVariantVoiceoverReady = `-- name: MarkScriptVariantVoiceoverReady :exec
UPDATE script_variants
SET status = 'voiceover_ready', error_message = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkScriptVariantVoiceoverReady(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markScriptVariantVoiceoverReady, id)
	return err
}

const markVoiceAuditionCompleted = `-- name: MarkVoiceAuditionCompleted :exec
UPDATE voice_auditions
SET
    status = 'completed',
    audio_storage_key = $2,
    sample_rate = $3,
    duration_ms = $4,
    error_message = NULL,
    updated_at = now()
WHERE id = $1
`

type MarkVoiceAuditionCompletedParams struct {
	ID              pgtype.UUID `json:"id"`
	AudioStorageKey pgtype.Text `json:"audio_storage_key"`
	SampleRate      pgtype.Int4 `json:"sample_rate"`
	DurationMs      pgtype.Int4 `json:"duration_ms"`
}

func (q *Queries) MarkVoiceAuditionCompleted(ctx context.Context, arg MarkVoiceAuditionCompletedParams) error {
	_, err := q.db.Exec(ctx, markVoiceAuditionCompleted,
		arg.ID,
		arg.AudioStorageKey,
		arg.SampleRate,
		arg.DurationMs,
	)
	return err
}

const markVoiceAuditionFailed = `-- name: MarkVoiceAuditionFailed :exec
UPDATE voice_auditions
SET status = 'failed', error_message = $2, updated_at = now()
WHERE id = $1
`

type MarkVoiceAuditionFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkVoiceAuditionFailed(ctx context.Context, arg MarkVoiceAuditionFailedParams) error {
	_, err := q.db.Exec(ctx, markVoiceAuditionFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markVoiceAuditionSynthesizing = `-- name: MarkVoiceAuditionSynthesizing :exec
UPDATE voice_auditions
SET status = 'synthesizing', error_message = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkVoiceAuditionSynthesizing(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markVoiceAuditionSynthesizing, id)
	return err
}

const markVoiceoverCompleted = `-- name: MarkVoiceoverCompleted :exec
UPDATE voiceovers
SET
    status = 'completed',
    storage_key = $2,
    sample_rate = $3,
    duration_ms = $4,
    error_message = NULL,
    updated_at = now()
WHERE id = $1
`

type MarkVoiceoverCompletedParams struct {
	ID         pgtype.UUID `json:"id"`
	StorageKey pgtype.Text `json:"storage_key"`
	SampleRate pgtype.Int4 `json:"sample_rate"`
	DurationMs pgtype.Int4 `json:"duration_ms"`
}

func (q *Queries) MarkVoiceoverCompleted(ctx context.Context, arg MarkVoiceoverCompletedParams) error {
	_, err := q.db.Exec(ctx, markVoiceoverCompleted,
		arg.ID,
		arg.StorageKey,
		arg.SampleRate,
		arg.DurationMs,
	)
	return err
}

const markVoiceoverFailed = `-- name: MarkVoiceoverFailed :exec
UPDATE voiceovers
SET status = 'failed', error_message = $2, updated_at = now()
WHERE id = $1
`

type MarkVoiceoverFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkVoiceoverFailed(ctx context.Context, arg MarkVoiceoverFailedParams) error {
	_, err := q.db.Exec(ctx, markVoiceoverFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markVoiceoverSynthesizing = `-- name: MarkVoiceoverSynthesizing :exec
UPDATE voiceovers
SET status = 'synthesizing', error_message = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkVoiceoverSynthesizing(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markVoiceoverSynthesizing, id)
	return err
}

const markVoiceoverTranscribing = `-- name: MarkVoiceoverTranscribing :exec
UPDATE voiceovers
SET status = 'transcribing', error_message = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkVoiceoverTranscribing(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markVoiceoverTranscribing, id)
	return err
}
