// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: voice_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultVoiceProfiles = `-- name: ClearDefaultVoiceProfiles :exec
UPDATE voice_profiles
SET is_default = FALSE, updated_at = now()
WHERE is_default = TRUE
`

func (q *Queries) ClearDefaultVoiceProfiles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultVoiceProfiles)
	return err
}

const createVoiceProfile = `-- name: CreateVoiceProfile :one
INSERT INTO voice_profiles (
    id,
    name,
    language,
    style_tags,
    reference_text,
    reference_audio_storage_key,
    reference_audio_file_name,
    reference_audio_mime_type,
    reference_audio_size,
    preview_text,
    status,
    is_default,
    created_by_user_id,
    updated_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, name, language, style_tags, reference_text, reference_audio_storage_key, reference_audio_file_name, reference_audio_mime_type, reference_audio_size, preview_text, preview_audio_storage_key, preview_status, preview_error, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type CreateVoiceProfileParams struct {
	ID                       pgtype.UUID `json:"id"`
	Name                     string      `json:"name"`
	Language                 string      `json:"language"`
	StyleTags                []byte      `json:"style_tags"`
	ReferenceText            string      `json:"reference_text"`
	ReferenceAudioStorageKey string      `json:"reference_audio_storage_key"`
	ReferenceAudioFileName   string      `json:"reference_audio_file_name"`
	ReferenceAudioMimeType   string      `json:"reference_audio_mime_type"`
	ReferenceAudioSize       int64       `json:"reference_audio_size"`
	PreviewText              string      `json:"preview_text"`
	Status                   string      `json:"status"`
	IsDefault                bool        `json:"is_default"`
	CreatedByUserID          pgtype.UUID `json:"created_by_user_id"`
	UpdatedByUserID          pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) CreateVoiceProfile(ctx context.Context, arg CreateVoiceProfileParams) (VoiceProfile, error) {
	row := q.db.QueryRow(ctx, createVoiceProfile,
		arg.ID,
		arg.Name,
		arg.Language,
		arg.StyleTags,
		arg.ReferenceText,
		arg.ReferenceAudioStorageKey,
		arg.ReferenceAudioFileName,
		arg.ReferenceAudioMimeType,
		arg.ReferenceAudioSize,
		arg.PreviewText,
		arg.Status,
		arg.IsDefault,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
	)
	var i VoiceProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Language,
		&i.StyleTags,
		&i.ReferenceText,
		&i.ReferenceAudioStorageKey,
		&i.ReferenceAudioFileName,
		&i.ReferenceAudioMimeType,
		&i.ReferenceAudioSize,
		&i.PreviewText,
		&i.PreviewAudioStorageKey,
		&i.PreviewStatus,
		&i.PreviewError,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVoiceProfile = `-- name: DeleteVoiceProfile :exec
DELETE FROM voice_profiles
WHERE id = $1
`

func (q *Queries) DeleteVoiceProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVoiceProfile, id)
	return err
}

const getVoiceProfileByID = `-- name: GetVoiceProfileByID :one
SELECT id, name, language, style_tags, reference_text, reference_audio_storage_key, reference_audio_file_name, reference_audio_mime_type, reference_audio_size, preview_text, preview_audio_storage_key, preview_status, preview_error, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at FROM voice_profiles
WHERE id = $1
`

func (q *Queries) GetVoiceProfileByID(ctx context.Context, id pgtype.UUID) (VoiceProfile, error) {
	row := q.db.QueryRow(ctx, getVoiceProfileByID, id)
	var i VoiceProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Language,
		&i.StyleTags,
		&i.ReferenceText,
		&i.ReferenceAudioStorageKey,
		&i.ReferenceAudioFileName,
		&i.ReferenceAudioMimeType,
		&i.ReferenceAudioSize,
		&i.PreviewText,
		&i.PreviewAudioStorageKey,
		&i.PreviewStatus,
		&i.PreviewError,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVoiceProfiles = `-- name: ListVoiceProfiles :many
SELECT id, name, language, style_tags, reference_text, reference_audio_storage_key, reference_audio_file_name, reference_audio_mime_type, reference_audio_size, preview_text, preview_audio_storage_key, preview_status, preview_error, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at FROM voice_profiles
ORDER BY is_default DESC, created_at ASC
`

func (q *Queries) ListVoiceProfiles(ctx context.Context) ([]VoiceProfile, error) {
	rows, err := q.db.Query(ctx, listVoiceProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoiceProfile
	for rows.Next() {
		var i VoiceProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Language,
			&i.StyleTags,
			&i.ReferenceText,
			&i.ReferenceAudioStorageKey,
			&i.ReferenceAudioFileName,
			&i.ReferenceAudioMimeType,
			&i.ReferenceAudioSize,
			&i.PreviewText,
			&i.PreviewAudioStorageKey,
			&i.PreviewStatus,
			&i.PreviewError,
			&i.Status,
			&i.IsDefault,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVoiceProfilePreviewFailed = `-- name: MarkVoiceProfilePreviewFailed :exec
UPDATE voice_profiles
SET
    preview_status = 'failed',
    preview_error = $2,
    updated_at = now()
WHERE id = $1
`

type MarkVoiceProfilePreviewFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	PreviewError pgtype.Text `json:"preview_error"`
}

func (q *Queries) MarkVoiceProfilePreviewFailed(ctx context.Context, arg MarkVoiceProfilePreviewFailedParams) error {
	_, err := q.db.Exec(ctx, markVoiceProfilePreviewFailed, arg.ID, arg.PreviewError)
	return err
}

const markVoiceProfilePreviewReady = `-- name: MarkVoiceProfilePreviewReady :exec
UPDATE voice_profiles
SET
    preview_status = 'ready',
    preview_audio_storage_key = $2,
    preview_error = NULL,
    updated_at = now()
WHERE id = $1
`

type MarkVoiceProfilePreviewReadyParams struct {
	ID                     pgtype.UUID `json:"id"`
	PreviewAudioStorageKey pgtype.Text `json:"preview_audio_storage_key"`
}

func (q *Queries) MarkVoiceProfilePreviewReady(ctx context.Context, arg MarkVoiceProfilePreviewReadyParams) error {
	_, err := q.db.Exec(ctx, markVoiceProfilePreviewReady, arg.ID, arg.PreviewAudioStorageKey)
	return err
}

const markVoiceProfilePreviewSynthesizing = `-- name: MarkVoiceProfilePreviewSynthesizing :exec
UPDATE voice_profiles
SET
    preview_status = 'processing',
    preview_error = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkVoiceProfilePreviewSynthesizing(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markVoiceProfilePreviewSynthesizing, id)
	return err
}

const queueVoiceProfilePreview = `-- name: QueueVoiceProfilePreview :exec
UPDATE voice_profiles
SET
    preview_status = 'queued',
    preview_audio_storage_key = NULL,
    preview_error = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) QueueVoiceProfilePreview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, queueVoiceProfilePreview, id)
	return err
}

const setDefaultVoiceProfile = `-- name: SetDefaultVoiceProfile :one
UPDATE voice_profiles
SET
    is_default = TRUE,
    updated_by_user_id = $2,
    updated_at = now()
WHERE id = $1
  AND status = 'enabled'
RETURNING id, name, language, style_tags, reference_text, reference_audio_storage_key, reference_audio_file_name, reference_audio_mime_type, reference_audio_size, preview_text, preview_audio_storage_key, preview_status, preview_error, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type SetDefaultVoiceProfileParams struct {
	ID              pgtype.UUID `json:"id"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) SetDefaultVoiceProfile(ctx context.Context, arg SetDefaultVoiceProfileParams) (VoiceProfile, error) {
	row := q.db.QueryRow(ctx, setDefaultVoiceProfile, arg.ID, arg.UpdatedByUserID)
	var i VoiceProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Language,
		&i.StyleTags,
		&i.ReferenceText,
		&i.ReferenceAudioStorageKey,
		&i.ReferenceAudioFileName,
		&i.ReferenceAudioMimeType,
		&i.ReferenceAudioSize,
		&i.PreviewText,
		&i.PreviewAudioStorageKey,
		&i.PreviewStatus,
		&i.PreviewError,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVoiceProfileMetadata = `-- name: UpdateVoiceProfileMetadata :one
UPDATE voice_profiles
SET
    name = $2,
    language = $3,
    style_tags = $4,
    reference_text = $5,
    preview_text = $6,
    status = $7,
    is_default = $8,
    updated_by_user_id = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, name, language, style_tags, reference_text, reference_audio_storage_key, reference_audio_file_name, reference_audio_mime_type, reference_audio_size, preview_text, preview_audio_storage_key, preview_status, preview_error, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type UpdateVoiceProfileMetadataParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Language        string      `json:"language"`
	StyleTags       []byte      `json:"style_tags"`
	ReferenceText   string      `json:"reference_text"`
	PreviewText     string      `json:"preview_text"`
	Status          string      `json:"status"`
	IsDefault       bool        `json:"is_default"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) UpdateVoiceProfileMetadata(ctx context.Context, arg UpdateVoiceProfileMetadataParams) (VoiceProfile, error) {
	row := q.db.QueryRow(ctx, updateVoiceProfileMetadata,
		arg.ID,
		arg.Name,
		arg.Language,
		arg.StyleTags,
		arg.ReferenceText,
		arg.PreviewText,
		arg.Status,
		arg.IsDefault,
		arg.UpdatedByUserID,
	)
	var i VoiceProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Language,
		&i.StyleTags,
		&i.ReferenceText,
		&i.ReferenceAudioStorageKey,
		&i.ReferenceAudioFileName,
		&i.ReferenceAudioMimeType,
		&i.ReferenceAudioSize,
		&i.PreviewText,
		&i.PreviewAudioStorageKey,
		&i.PreviewStatus,
		&i.PreviewError,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVoiceProfileWithReference = `-- name: UpdateVoiceProfileWithReference :one
UPDATE voice_profiles
SET
    name = $2,
    language = $3,
    style_tags = $4,
    reference_text = $5,
    reference_audio_storage_key = $6,
    reference_audio_file_name = $7,
    reference_audio_mime_type = $8,
    reference_audio_size = $9,
    preview_text = $10,
    status = $11,
    is_default = $12,
    updated_by_user_id = $13,
    updated_at = now()
WHERE id = $1
RETURNING id, name, language, style_tags, reference_text, reference_audio_storage_key, reference_audio_file_name, reference_audio_mime_type, reference_audio_size, preview_text, preview_audio_storage_key, preview_status, preview_error, status, is_default, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type UpdateVoiceProfileWithReferenceParams struct {
	ID                       pgtype.UUID `json:"id"`
	Name                     string      `json:"name"`
	Language                 string      `json:"language"`
	StyleTags                []byte      `json:"style_tags"`
	ReferenceText            string      `json:"reference_text"`
	ReferenceAudioStorageKey string      `json:"reference_audio_storage_key"`
	ReferenceAudioFileName   string      `json:"reference_audio_file_name"`
	ReferenceAudioMimeType   string      `json:"reference_audio_mime_type"`
	ReferenceAudioSize       int64       `json:"reference_audio_size"`
	PreviewText              string      `json:"preview_text"`
	Status                   string      `json:"status"`
	IsDefault                bool        `json:"is_default"`
	UpdatedByUserID          pgtype.UUID `json:"updated_by_user_id"`
}

func (q *Queries) UpdateVoiceProfileWithReference(ctx context.Context, arg UpdateVoiceProfileWithReferenceParams) (VoiceProfile, error) {
	row := q.db.QueryRow(ctx, updateVoiceProfileWithReference,
		arg.ID,
		arg.Name,
		arg.Language,
		arg.StyleTags,
		arg.ReferenceText,
		arg.ReferenceAudioStorageKey,
		arg.ReferenceAudioFileName,
		arg.ReferenceAudioMimeType,
		arg.ReferenceAudioSize,
		arg.PreviewText,
		arg.Status,
		arg.IsDefault,
		arg.UpdatedByUserID,
	)
	var i VoiceProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Language,
		&i.StyleTags,
		&i.ReferenceText,
		&i.ReferenceAudioStorageKey,
		&i.ReferenceAudioFileName,
		&i.ReferenceAudioMimeType,
		&i.ReferenceAudioSize,
		&i.PreviewText,
		&i.PreviewAudioStorageKey,
		&i.PreviewStatus,
		&i.PreviewError,
		&i.Status,
		&i.IsDefault,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
